___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [49]:
ranarr = np.random.randint(0,50,10)
print(ranarr)
print(ranarr.max())
print(ranarr.min())
print(ranarr.argmax())
print(ranarr.argmin())

[14 17 46 44 30  4 45  1 16  5]
46
1
2
7


#### Create an array of 10 ones

In [3]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [4]:
5*np.ones(10)

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand(1)

array([ 0.94550508])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [13]:
np.random.rand(25)

array([ 0.07604605,  0.99428627,  0.45701433,  0.53108426,  0.27377662,
        0.30327265,  0.64472532,  0.60341829,  0.02014236,  0.41868845,
        0.0293339 ,  0.98342004,  0.61721115,  0.21282195,  0.09312347,
        0.40350441,  0.00214307,  0.3663429 ,  0.59748009,  0.25816886,
        0.87675393,  0.29516744,  0.44563062,  0.83933363,  0.66792745])

#### Create the following matrix:

In [15]:
np.random.rand(100).reshape(10,10)

array([[ 0.41634628,  0.93258733,  0.05443514,  0.98545659,  0.12832113,
         0.03639641,  0.2492564 ,  0.53278355,  0.75999117,  0.97949587],
       [ 0.39017594,  0.3609501 ,  0.84259441,  0.12726739,  0.51600021,
         0.89287026,  0.91365946,  0.39498437,  0.28585994,  0.97206495],
       [ 0.46978399,  0.59839715,  0.99930282,  0.7313172 ,  0.24117205,
         0.73434531,  0.2100053 ,  0.4666076 ,  0.44971214,  0.17690664],
       [ 0.89989785,  0.38966422,  0.24399732,  0.35669604,  0.14493196,
         0.28998697,  0.32630066,  0.29283253,  0.93032203,  0.5958971 ],
       [ 0.66996724,  0.7569962 ,  0.53650522,  0.6683331 ,  0.94844816,
         0.09965168,  0.70357591,  0.03944966,  0.19503559,  0.96641225],
       [ 0.6932638 ,  0.78246156,  0.31825032,  0.88169282,  0.33833156,
         0.60245601,  0.73748966,  0.70882811,  0.51959087,  0.28448923],
       [ 0.38635003,  0.44420174,  0.09080559,  0.67605829,  0.4685682 ,
         0.47834007,  0.27917661,  0.72656169

#### Create an array of 20 linearly spaced points between 0 and 1:

In [17]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [18]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [24]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [25]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [26]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [29]:
sum(mat)

array([55, 60, 65, 70, 75])

#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!